version: '3'
services:
  api:
    container_name: imersion_FullCycle_nestjs_api
    build: .
    command: "sh -c 'npm install && npm run start:dev'"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/api
#sh -c to can use && to more commands
